modLoader="javafml"
loaderVersion="${loader_version}"
issueTrackerURL="https://github.com/mekanism/Mekanism/issues"
license="MIT"

[[mods]]
    modId="mekanismadditions"
    version="${file.jarVersion}"
    displayName="Mekanism: Additions"
    displayURL="https://aidancbrady.com/mekanism/"
    authors="Aidancbrady, Thommy101, Thiakil, pupnewfster, dizzyd"
    credits="unpairedbracket, CyanideX, Ridanisaurus and many others"
    logoFile="logo.png"
    description='''Additions module for Mekanism, contains miscellaneous things that do not thematically fit in the other modules.'''

[[dependencies.mekanismadditions]]
    modId="mekanism"
    type="required"
    versionRange="[${file.jarVersion}]"
    ordering="AFTER"
    side="BOTH"