modLoader="javafml"
loaderVersion="${loader_version_range}"
issueTrackerURL="https://github.com/Team-EnderIO/EnderIO/issues"
license="CC0"

[[mods]]
modId="enderio_conduits_tests"
version="${mod_version}"
displayName="Ender IO Conduits - Game Tests"
authors="CrazyPants, tterrag, HenryLoenwind, MatthiasM, CyanideX, EpicSquid, Rover656, HypherionSA, liliandev, Ferri_Arnus, dphaldes"
description="Game Tests for Ender IO Conduits"
displayURL="https://enderio.com/"
logoFile="logo.png"

[[dependencies.enderio_conduits]]
modId="minecraft"
type="required"
versionRange="${mcversion}"
side="BOTH"

[[dependencies.enderio_conduits]]
modId="neoforge"
type="required"
versionRange="${neo_version}"
side="BOTH"

[[dependencies.enderio_conduits]]
modId="endercore"
type="required"
versionRange="${mod_version}"
side="BOTH"

[[dependencies.enderio_conduits]]
modId="enderio_base"
type="required"
versionRange="${mod_version}"
side="BOTH"

[[dependencies.enderio_conduits]]
modId="enderio_conduits"
type="required"
versionRange="${mod_version}"
side="BOTH"
